# Default values for cloud-provider-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

account-service:
  attributeProviderFile:
  idp:
    host: https://logindev.ill.fr/auth/realms/ILL/.well-known/openid-configuration
    clientId: visadev
    loginField: preferred_username
  service:
    nodePorts:
      api: 32304
      nodeJSDebug: 32405


kubernetesRequestHelperFile:

dockerSecretFile:

nodeSelector: {}

tolerations: []

affinity: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi


logLevel: debug

cloud-provider-kubernetes:
  kubernetesHost: 192.168.1.56


desktop-service:
  service:
    nodePorts:
      socket: 32403
  webServerHost: 0.0.0.0

apache:
  vhostsConfigMap: panosc-portal-demo-vhosts

global:
  namespace:
    creation: true
    name: panosc-portal

  database:
    cloudProviderKubernetes:
      username: cloud-provider-kubernetes
      password: cloud-provider-kubernetes
      databaseName: cloud-provider-kubernetes
      schema: cloud-provider-kubernetes
    cloudService:
      username: cloud-service
      password: cloud-service
      databaseName: cloud-service
      schema: cloud-service
    desktopService:
      username: desktop-service
      password: desktop-service
      databaseName: desktop-service
      schema: desktop-service
    accountService:
      username: account-service
      password: account-service
      databaseName: account-service
      schema: account-service

  #imagePullSecrets: []
  #nameOverride: ""
  #fullnameOverride: ""

  #serviceAccount:
  #  # Specifies whether a service account should be created
  #  create: true
  #  # Annotations to add to the service account
  #  annotations: {}
  #  # The name of the service account to use.
  #  # If not set and create is true, a name is generated using the fullname template
  #  name:

  #podSecurityContext: {}
  # fsGroup: 2000

  #securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



#ingress:
#  enabled: false
#  annotations: {}
#    # kubernetes.io/ingress.class: nginx
#    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths: []
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local







