# Default values for cloud-provider-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


kubernetesRequestHelperFile:

dockerSecretFile:

nodeSelector: {}

tolerations: []

affinity: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

cloud-provider-kubernetes:
  database:
    username: test
    password: test
  namespace:
    portal:
      creation: false

logLevel: debug

global:
  namespace:
    creation: true
    name: panosc-portal

  database:
    cloudProviderKubernetes:
      username: cloud-provider-kubernetes
      password: test
      databaseName: cloud-provider-kubernetes
      schema: cloud-provider-kubernetes

  #imagePullSecrets: []
  #nameOverride: ""
  #fullnameOverride: ""

  #serviceAccount:
  #  # Specifies whether a service account should be created
  #  create: true
  #  # Annotations to add to the service account
  #  annotations: {}
  #  # The name of the service account to use.
  #  # If not set and create is true, a name is generated using the fullname template
  #  name:

  #podSecurityContext: {}
  # fsGroup: 2000

  #securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



#ingress:
#  enabled: false
#  annotations: {}
#    # kubernetes.io/ingress.class: nginx
#    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths: []
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local







