# Default values for cloud-provider-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: panosc/cloud-provider-kubernetes
  dockerTag: testing
  pullPolicy: IfNotPresent

service:
  nodePorts:
    api : 32300
    nodeJSDebug: 32401

namespace:
  instances:
    creation: true
    name: panosc-instances

kubernetesRequestHelperFile:

dockerSecretFile:

nodeSelector: {}

tolerations: []

affinity: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


logLevel: debug


global:
  namespace:
      name: default


  database:
    host: panosc-postgres
    port: 5432
    type: postgres
    log: false
    sync: false
    cloudProviderKubernetes:
      username: cloud-provider-kubernetes
      password:
      databaseName: cloud-provider-kubernetes
      schema: cloud-provider-kubernetes


#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""

#serviceAccount:
#  # Specifies whether a service account should be created
#  create: true
#  # Annotations to add to the service account
#  annotations: {}
#  # The name of the service account to use.
#  # If not set and create is true, a name is generated using the fullname template
#  name:

#podSecurityContext: {}
  # fsGroup: 2000

#securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



#ingress:
#  enabled: false
#  annotations: {}
#    # kubernetes.io/ingress.class: nginx
#    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths: []
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local








