apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "desktop-service-web-test-client.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "desktop-service-web-test-client.labels" . | nindent 4 }}
data:
  DESKTOP_SERVICE_WEB_TEST_CLIENT_VDI_HOST: {{ .Values.vdiUrl | quote}}