apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "desktop-service-web-test-client.name" . }}-vhosts
  namespace: {{ .Release.Namespace}}
  labels: {{- include "desktop-service-web-test-client.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "files/*.conf").AsConfig | indent 4 }}