apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panosc-postgres.name" . }}-config
  namespace: {{.Values.namespace.portal.name}}
  labels:
  {{- include "panosc-postgres.labels" . | nindent 4 }}
data:
  POSTGRES_HOST_AUTH_METHOD: "trust"