apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panosc-postgres.name" . }}-secret
  namespace: {{.Values.global.namespace.name}}
  labels:
    {{- include "panosc-postgres.labels" . | nindent 4 }}
data:
  CLOUD_PROVIDER_K8S_DATABASE_PASSWORD: {{ .Values.global.database.cloudProviderKubernetes.password | b64enc | quote}}
  #CLOUD_SERVICE_DATABASE_PASSWORD:
