apiVersion: v1
kind: Secret
metadata:
  name: {{ include "panosc-postgres.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panosc-postgres.labels" . | nindent 4 }}
data:
  CLOUD_PROVIDER_K8S_DATABASE_PASSWORD: {{ .Values.global.database.cloudProviderKubernetes.password | b64enc | quote}}
  CLOUD_SERVICE_DATABASE_PASSWORD: {{ .Values.global.database.cloudService.password | b64enc | quote}}
  DESKTOP_SERVICE_DATABASE_PASSWORD: {{ .Values.global.database.desktopService.password | b64enc | quote}}
  ACCOUNT_SERVICE_DATABASE_PASSWORD: {{ .Values.global.database.accountService.password | b64enc | quote}}

