apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panosc-postgres.name" . }}-shconfig
  namespace: {{.Values.namespace.portal.name}}
  labels:
  {{- include "panosc-postgres.labels" . | nindent 4 }}
data:
{{(.Files.Glob "postgres-config-files/*.sh").AsConfig | indent 4 }}
