apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panosc-postgres.name" . }}-sqldump
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "panosc-postgres.labels" . | nindent 4 }}
data:
{{(.Files.Glob "postgres-config-files/*.sql").AsConfig | indent 4 }}

