apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-provider-kubernetes.fullname" . }}-config
  namespace: {{ .Values.namespace.portal.name }}
  labels:
    {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}
data:
  CLOUD_PROVIDER_K8S_DATABASE_HOST: {{ .Values.database.host | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_PORT: {{ .Values.database.port | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_TYPE: {{ .Values.database.type | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_NAME: {{ .Values.database.databaseName | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_SCHEMA: {{ .Values.database.schema | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_LOGGING: {{ .Values.database.log | quote }}
  CLOUD_PROVIDER_K8S_DATABASE_SYNCHRONIZE: {{ .Values.database.sync | quote }}
  CLOUD_PROVIDER_K8S_LOG_LEVEL: {{ .Values.logLevel | quote }}
  {{- if .Values.kubernetesRequestHelperFile }}
  CLOUD_PROVIDER_K8S_KUBERNETES_REQUEST_HELPER: helper/k8s-request-helper.js
  {{ end }}
  {{- if .Values.dockerSecretFile }}
  CLOUD_PROVIDER_K8S_KUBERNETES_SECRETS_CONFIG: secrets/docker-repo-secrets.json
  {{ end }}
