{{- if  .Values.dockerSecretFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-provider-kubernetes.name" . }}-dockersecrets-config
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}
data:
  docker-repo-secrets.json: |
{{ .Values.dockerSecretFile | indent 4 }}
  {{ end }}