{{- if .Values.kubernetesRequestHelperFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-provider-kubernetes.name" . }}-helper-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}
data:
  k8s-request-helper.js: |-
{{  .Values.kubernetesRequestHelperFile | indent 4 }}
  {{ end }}