apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloud-provider-kubernetes.name" . }}-rolebinding
  labels:
  {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "cloud-provider-kubernetes.name" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cloud-provider-kubernetes-sa
    namespace: {{ .Release.Namespace }}