apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-provider-kubernetes.fullname" . }}-secret
  namespace: {{ .Values.namespace.portal.name }}
  labels:
    {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}
data:
  CLOUD_PROVIDER_K8S_DATABASE_USERNAME: {{ .Values.database.username | b64enc | quote}}
  CLOUD_PROVIDER_K8S_DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote}}
