apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-provider-kubernetes.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}
data:
  CLOUD_PROVIDER_K8S_DATABASE_USERNAME: {{ .Values.global.database.cloudProviderKubernetes.username | b64enc | quote}}
  CLOUD_PROVIDER_K8S_DATABASE_PASSWORD: {{ .Values.global.database.cloudProviderKubernetes.password | b64enc | quote}}
