apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-provider-kubernetes-sa
  namespace: {{ .Values.namespace.portal.name }}
  labels:
    {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}