apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-provider-kubernetes.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: api
      port: 3000
      nodePort: {{ .Values.service.nodePorts.api }}
   {{- if .Values.service.nodePorts.nodeJSDebug}}
    - name: debug
      port: 9229
      nodePort: {{.Values.service.nodePorts.nodeJSDebug}}
  {{- end }}
  selector:
    {{- include "cloud-provider-kubernetes.selectorLabels" . | nindent 4 }}
