apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloud-provider-kubernetes.name" . }}-sa
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}