apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-provider-kubernetes.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-provider-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: api
      targetPort: api
      port: {{ .Values.service.apiPort }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.api }}
      nodePort: {{ .Values.service.nodePorts.api }}
    {{- end }}
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePorts.nodeJSDebug}}
    - name: debug
      targetPort: debug
      port: 9229
      nodePort: {{.Values.service.nodePorts.nodeJSDebug}}
  {{- end }}
  selector:
    {{- include "cloud-provider-kubernetes.selectorLabels" . | nindent 4 }}
