apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desktop-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "desktop-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "desktop-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "desktop-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.dockerTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 8085
            - name: socket
              containerPort: 8087
          envFrom:
            - configMapRef:
                name: {{ include "desktop-service.name" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
