{{- if  .Files.Glob "files/*.conf" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "panosc-portal-demo.name" . }}-vhosts
  labels: {{- include "panosc-portal-demo.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "files/*.conf").AsConfig | indent 2 }}
  {{ end }}