apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-service.name" . }}-config
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "cloud-service.labels" . | nindent 4 }}
data:
  CLOUD_SERVICE_DATABASE_HOST: {{ .Values.global.database.host | quote }}
  CLOUD_SERVICE_DATABASE_PORT: {{ .Values.global.database.port | quote }}
  CLOUD_SERVICE_DATABASE_TYPE: {{ .Values.global.database.type | quote }}
  CLOUD_SERVICE_DATABASE_NAME: {{ .Values.global.database.cloudService.databaseName | quote }}
  CLOUD_SERVICE_DATABASE_SCHEMA: {{ .Values.global.database.cloudService.schema | quote }}
  CLOUD_SERVICE_DATABASE_LOGGING: "false"
  CLOUD_SERVICE_DATABASE_SYNCHRONIZE: "false"
  CLOUD_SERVICE_LOG_LEVEL: "debug"
