apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-service.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cloud-service.labels" . | nindent 4 }}
data:
  CLOUD_SERVICE_DATABASE_USERNAME: {{ .Values.global.database.cloudService.username | b64enc| quote }}
  CLOUD_SERVICE_DATABASE_PASSWORD: {{ .Values.global.database.cloudService.password | b64enc| quote }}

