apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-service.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
data:
  API_SERVICE_ACCOUNT_SERVICE_HOST: {{ .Values.global.accountService.host }}
  API_SERVICE_ACCOUNT_SERVICE_PORT: {{ .Values.global.accountService.port }}
  API_SERVICE_CLOUD_SERVICE_HOST: {{ .Values.global.cloudService.host }}
  API_SERVICE_CLOUD_SERVICE_PORT: {{ .Values.global.cloudService.port }}
