{{- if and .Values.idp.attributeProviderFile  (not .Values.idp.attributeProviderConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.name" . }}-attribute-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "account-service.labels" . | nindent 4 }}
data:
  attribute.js: |-
{{ .Values.idp.attributeProviderFile | indent 4 }}
{{ end }}