{{- if  .Values.attributeProviderFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.name" . }}-attribute-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "account-service.labels" . | nindent 4 }}
data:
  attribute-config.js: |-
{{ .Values.attributeProviderFile | indent 4 }}
{{ end }}