apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
data:
  ACCOUNT_SERVICE_DATABASE_HOST: {{ .Values.global.database.host | quote }}
  ACCOUNT_SERVICE_DATABASE_PORT: {{ .Values.global.database.port | quote }}
  ACCOUNT_SERVICE_DATABASE_TYPE: {{ .Values.global.database.type | quote }}
  ACCOUNT_SERVICE_DATABASE_NAME: {{ .Values.global.database.accountService.databaseName | quote }}
  ACCOUNT_SERVICE_DATABASE_SCHEMA: {{ .Values.global.database.accountService.schema | quote }}
  ACCOUNT_SERVICE_DATABASE_LOGGING: {{ .Values.global.database.log | quote }}
  ACCOUNT_SERVICE_DATABASE_SYNCHRONIZE: {{ .Values.global.database.sync | quote }}
  ACCOUNT_SERVICE_LOG_LEVEL: {{ .Values.logLevel | quote }}
  ACCOUNT_SERVICE_IDP: {{ .Values.idp.url | quote }}
  ACCOUNT_SERVICE_CLIENT_ID: {{ .Values.idp.clientId | quote }}
  ACCOUNT_SERVICE_LOGIN_FIELD: {{ .Values.idp.loginField | quote }}
  ACCOUNT_SERVICE_DEFAULT_ROLE_ID: {{ .Values.defaultRoleId | quote}}
  ACCOUNT_SERVICE_ATTRIBUTE_PROVIDER: "/home/node/app/attribute/attribute.js"
