apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.name" . }}-config
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
data:
  ACCOUNT_SERVICE_DATABASE_HOST: {{ .Values.global.database.host | quote }}
  ACCOUNT_SERVICE_DATABASE_PORT: {{ .Values.global.database.port | quote }}
  ACCOUNT_SERVICE_DATABASE_TYPE: {{ .Values.global.database.type | quote }}
  ACCOUNT_SERVICE_DATABASE_NAME: {{ .Values.global.database.accountService.databaseName | quote }}
  ACCOUNT_SERVICE_DATABASE_SCHEMA: {{ .Values.global.database.accountService.schema | quote }}
  ACCOUNT_SERVICE_DATABASE_LOGGING: {{ .Values.global.database.log | quote }}
  ACCOUNT_SERVICE_DATABASE_SYNCHRONIZE: {{ .Values.global.database.sync | quote }}
  ACCOUNT_SERVICE_LOG_LEVEL: {{ .Values.logLevel | quote }}
