apiVersion: v1
kind: Secret
metadata:
  name: {{ include "account-service.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
data:
  ACCOUNT_SERVICE_DATABASE_USERNAME: {{ .Values.global.database.accountService.username | b64enc | quote}}
  ACCOUNT_SERVICE_DATABASE_PASSWORD: {{ .Values.global.database.accountService.password | b64enc | quote}}
